apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltis-basic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voltis-basic
  template:
    metadata:
      labels:
        app: voltis-basic
    spec:
      containers:
        - name: app
          image: voltis-basic:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"

